name: Hello World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello Step
        run: |
            echo "Welcome to GitHub Actions"
            echo "I am Suresh Kumar"
            echo "Working as a DevOps Engineer and Cloud Engineer in MNC Company"
    
   
  
