name: Deploy html to AWS S3 bucket
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code from repo
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID1 }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY1 }}
        aws-region: ap-south-1

    - name: Code Static Copy to S3 bucket.
      run: |
         aws s3 sync ./ s3://w3-gha-website-demo/ \
         --exclude "*" \
         --include "index.html"
         
    
        
      
    
   
  
