name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Phase
        run: echo "A demo build"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Phase
        run: echo "Running test cases"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Phase
        run: echo "Deploping Phase"
    
   
  
