name: Context Variables Demo
on: push
jobs:
  context-demo:
   runs-on: ubuntu-latest
   steps:
     - name: Use Context Variables
       run: |
         echo "This workflow is triggered by ${{ github.actor }}"
         echo "The  Repository Name is :- ${{ github.repository }}"
         echo "The Branch Name is:- ${{ github.ref_name }}"
         
     - name: Print all Variables under github
       run: echo "${{ toJson(github) }}"

     - name: Print Environment Variables
       run: echo "$GITHUB_SHA"
        
