name: Env-demo
on: workflow_dispatch
env: 
  APP_ENV: "dev"
jobs:
  env-demo:
   runs-on: ubuntu-latest
   steps:
     - name: Connecting to environment
       run: echo "Application is connection to $APP_ENV"
  
  
