name: If Demo
on: workflow_dispatch

      branches:
       - master
       - dev
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run if branch is master
        if: github.ref_name == 'master' 
        run: echo "Running for master branch."
      - name: Run this Step
        run: echo "Running this step."
        
