name: Inputs Demo
on: 
  workflow_dispatch:
    inputs:
      environment:
       description: Choose the Environment to Deploy the app
       required: true
       default: dev

 jobs:
    inputs-demo:
     runs-on: ubuntu-latest
     steps:
     - name: Deploy the Applicatoin 
       run: echo "Deploying the Application to ${{ inputs.environment }}"
         
       
      
    
 
