name: Or Condition Demo
on: push
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Lehar Aashish or sureshkumar-devops
        if: github.actor == 'sureshkumar-devops' || 'Lehar Aashish'
        run: echo "It is triggered by either sureshkumar-devops Or Lehar Aashish"
      - name: Run if condition fails
        run: echo "if condition fails"
        
        
