name: Or Condition Demo
on: workflow_dispatch
jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Run for Lehar Aashish or sureshkumar-devops
        if: github.actor == 'sureshkumar-devops' || github.actor == 'Lehar-Aashish'
        run: echo "It is triggered by either sureshkumar-devops Or Lehar Aashish"
    
        
        
