name: Outputs Demo
on: workflow_dispatch
jobs:
  build:
    outputs:
      artifact_version: ${{ steps.step1.outputs.version }} 
      
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        id: step1
        run: echo "version=0.0.1" >> $GITHUB_OUTPUT
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the Application
        run: echo "we are deploying the application with version ${{ needs.build.outputs.artifact_version }}"
        
   
    
